workflow clustered

diff --git a/Assignment2/snakefile b/Assignment2/snakefile
--- a/Assignment2/snakefile
+++ b/Assignment2/snakefile
@@ -14,19 +14,21 @@ snpeff_jar = "/staging/leuven/stg_00079/teaching/I0U19a_conda_2024/share/snpeff-
 snpeff_genome = 'hg38'
 snpeff_db_folder = "/staging/leuven/stg_00079/teaching/1000genomes/hg38"
 
+#rules that will run on main job instead of the cluster,generally dont benefit from parallisation
+localrules: all, SNP_calling, SNP_norm_filt, snpeff, extract_snps, snp_heatmap
+
 #rule stating what the end goal is, 
 #these endpoint will determine which graphs are actually checked for dependecies
 #anything not requested will have itself or its dependencies generated
 rule all:
     input:
         fastqc_zip=expand("1_fastqc/{sample}_fastqc.zip", sample=sample_names),
-        summary_png=expand("1_fastqc/{sample}_fastqc/summary.png", sample=sample_names),
-        rep1=expand("1_fastqc/{sample}_fastqc/Images/per_base_quality.png", sample=sample_names),
+        BWA=expand("2_bwa/{sample}.bam", sample=sample_names),
+        # summary_png=expand("1_fastqc/{sample}_fastqc/summary.png", sample=sample_names),
         vcf="3_samtools/snps.vcf",
-        cleaned_vcf="4_cleaned/snps.cleaned.vcf",
         snpeff = "5_snpeff/snps.annotated.vcf",       
         genes_vcf="genes.vcf",
-        heatmap_image="7_heatmap/snps_heatmap.png"
+        # heatmap_image="snps_heatmap.png"
 
 # Rule for performing FastQC
 rule fastqc:
@@ -46,41 +48,38 @@ rule fastqc:
 
     shell:
         """
-        echo "Input Fastq: {sample} "
+        export PATH=/lustre1/project/stg_00079/teaching/I0U19a_conda_2024/bin:$PATH
+    
+        echo "Input Fastq: {wildcards.sample} "
+        
+        #extract the fastqc
         fastqc -o 1_fastqc {input} --extract
 
-        echo "Unzip the output"
-        ( cd 1_fastqc ; unzip -o {wildcards.sample}_fastqc.zip )
+        # # Check if it is in FASTQ format
+        # first_line=$(head -n 1 {input.fq})
+        # third_line=$(sed -n '3p' {input.fq})
 
-        # grep WARN 1_fastqc/{wildcards.sample}_fastqc/summary.txt && false
-                # Check if the HTML report is generated
-        if [ ! -f 1_fastqc/{wildcards.sample}_fastqc.html ]; then
-            echo "Error: HTML report not generated."
-            exit 1
+        # if ! [[ $first_line == "@"* && $second_line != "+" && $third_line == "+"* ]]; then
+        #     echo "File is not in FASTQ format."
+        #     false
+        # fi
+
+        # #check that file is not truncated
+        # if [ $(tail -n 4 {input.fq} | head -n 1 | cut -c1) = "@" ]; then
+        #     echo "Fourth last line does not begin with '@'!"
+        #     false
+        # fi
+
+        if grep FAIL {output.rep3}; then
+            echo "Summary contains Fails!"
+            false
         fi
-
-        # Check if the summary data file is present
-        if [ ! -f 1_fastqc/{wildcards.sample}_fastqc/fastqc_data.txt ]; then
-            echo "Error: Summary data file not generated."
-            exit 1
-        fi
-
-        # Check if the required images are generated
-        if [ ! -f 1_fastqc/{wildcards.sample}_fastqc/Images/per_base_quality.png ] || \
-           [ ! -f 1_fastqc/{wildcards.sample}_fastqc/Images/per_base_sequence_content.png ]; then
-            echo "Error: Required images not generated."
-            exit 1
-        fi
-
-        # Check if the summary text file is generated and contains no warnings
-        if [ ! -f 1_fastqc/{wildcards.sample}_fastqc/summary.txt ]; then
-            echo "Error: Summary text file not generated."
-            exit 1
-        elif grep -q "WARN" 1_fastqc/{wildcards.sample}_fastqc/summary.txt; then
-            echo "Error: Summary text file contains warnings."
-            exit 1
+        #these warnings arent severe as bias can be introduced by the adapters used
+        if grep WARN {output.rep3}; then
+            echo "Summary contains warnings!"
         fi
         """
+
 
 # Rule for performing BWA
 rule bwa:
@@ -93,19 +92,41 @@ rule bwa:
         db=BWA_DB_chr21,
     shell:
         """
-        echo "Performing BWA on: {sample} "
-        bwa mem {params} {input} \
+        export PATH=/lustre1/project/stg_00079/teaching/I0U19a_conda_2024/bin:$PATH
+
+        echo "Performing BWA on: {wildcards.sample} "
+
+        # Check if there are at least 24 files in the params.db beginning with "sequence"
+        if [ $(ls -1 {params.db}/sequence* 2>/dev/null | wc -l) -ge 24 ]; then
+            echo "Error: Less than 24 files beginning with 'sequence' found."
+            false
+        fi
+
+        # Check if a file beginning with "cytoBand" exists
+        if test -e "${params.db}/cytoBand"*; then
+            echo "Error: No file beginning with 'cytoBand' found."
+            false
+        fi
+
+        # Check if a file beginning with "pwms" exists
+        if test -e "${params.db}/pwms"*; then
+            echo "Error: No file beginning with 'pwms' found."
+            false
+        fi
+
+        # Check if a file beginning with "snpEffectPredictor" exists
+        if test -e "${params.db}/snpEffectPredictor"*; then
+            echo "Error: No file beginning with 'snpEffectPredictor' found."
+            false
+        fi
+
+        bwa mem {params.db} {input} \
             | samtools sort - \
             > {output.bam}
         samtools index {output.bam}
 
-   
-        """
-        # if [ -f {output.bam} ] && [ -f {output.bai} ]; then
-        #     echo "BAM file created sucessfully."
-        # else
-        #     echo "Error: BAM file missing: {output.bam}"
-        #     exit 1     
+  
+        """      
 
 # Rule for SNP calling using bcftools
 rule SNP_calling:
@@ -116,14 +137,12 @@ rule SNP_calling:
         vcf="3_samtools/snps.vcf",
     shell:
         """
-        echo "Performing SNP calling on: {sample} "
+        echo "Performing SNP calling"
         bcftools mpileup -Ou -f {input.db} {input.bams} \
              | bcftools call -mv -Ov -o {output.vcf}
 
         # Check if the VCF file was created
-        if [ -f {output.vcf} ]; then
-            echo "VCF was generated."
-        else
+        if ! [ -f {output.vcf} ]; then
             echo "Error: SNP calling failed"
             exit 1
         fi
@@ -138,7 +157,7 @@ rule SNP_norm_filt:
         vcf="4_cleaned/snps.cleaned.vcf"
     shell:
         """
-        echo "Normalizing and filtering: {sample} "
+        echo "Normalizing and filtering"
         ( cat {input.vcf} \
            | vt decompose - \
            | vt normalize -n -r {input.db} - \
@@ -163,7 +182,7 @@ rule snpeff:
         genetxt = "5_snpeff/snpEff_genes.txt",
     shell:
         """
-        echo "Annotating: {sample} "
+        echo "Annotating"
         mkdir -p 5_snpeff
 
         java -Xmx4096m -jar \
@@ -176,54 +195,36 @@ rule snpeff:
 
         """
 
+# rule fastqc_report_image:
+#     input:
+#         summarytxt = "1_fastqc/{sample}_fastqc/summary.txt"
+#     output:
+#         statuspng = report("1_fastqc/{sample}_fastqc/summary.png",
+#                          category='Fastqc',
+#                          subcategory='Status',
+#                          labels={"sample": "{sample}"})
 
+#     run:
+#         import pandas as pd
+#         import seaborn as sns
+#         import matplotlib.pyplot as plt
 
-# Rule for creating an image with a heatmap showing the number of SNPs per individual
-rule snp_heatmap:
-    input:
-        vcf="5_snpeff/snps.annotated.vcf",
-    output:
-        heatmap_image="7_heatmap/snps_heatmap.png",
-    shell:
-        """
-        bcftools query -l {input.vcf} > samples.txt
-        bcftools query -f '%CHROM\t%POS[\t%GT]\n' {input.vcf} | grep -v '#' | cut -f 3- > genotypes.txt
-        paste samples.txt genotypes.txt | awk '{print $1,$(NF-1),$NF}' | sort | uniq -c | awk '{print $2,$3,$1}' > snps_per_individual.txt
-        awk '{print $1}' snps_per_individual.txt > individuals.txt
-        awk '{print $2}' snps_per_individual.txt > snps.txt
-        python heatmap.py individuals.txt snps.txt {output.heatmap_image}
-        """
+#         #load data
+#         data = pd.read_csv(input.summarytxt, sep="\t", header=None)
+#         data.columns = ['status', 'test', 'sample']
 
-rule fastqc_report_image:
-    input:
-        summarytxt = "1_fastqc/{sample}_fastqc/summary.txt"
-    output:
-        statuspng = report("1_fastqc/{sample}_fastqc/summary.png",
-                         category='Fastqc',
-                         subcategory='Status',
-                         labels={"sample": "{sample}"})
+#         #assign dummy x value for scatterplot
+#         data['x'] = 1
 
-    run:
-        import pandas as pd
-        import seaborn as sns
-        import matplotlib.pyplot as plt
-
-        #load data
-        data = pd.read_csv(input.summarytxt, sep="\t", header=None)
-        data.columns = ['status', 'test', 'sample']
-
-        #assign dummy x value for scatterplot
-        data['x'] = 1
-
-        #create image
-        fig = plt.figure(figsize=(4,5))
-        ax = plt.gca()
-        sns.scatterplot(data, x='x', y='test', hue='status', s=200, ax=ax)
-        ax.get_xaxis().set_visible(False)
-        ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
-        plt.tight_layout()
-        plt.title(wildcards.sample)
-        plt.savefig(output.statuspng)
+#         #create image
+#         fig = plt.figure(figsize=(4,5))
+#         ax = plt.gca()
+#         sns.scatterplot(data, x='x', y='test', hue='status', s=200, ax=ax)
+#         ax.get_xaxis().set_visible(False)
+#         ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
+#         plt.tight_layout()
+#         plt.title(wildcards.sample)
+#         plt.savefig(output.statuspng)
 
 # Rule for extracting SNPs associated with APP, SOD21, and DYRK1A into a new VCF file
 rule extract_snps:
@@ -234,6 +235,25 @@ rule extract_snps:
     shell:
         """
         # Extract SNPs associated with APP, SOD21, and DYRK1A from the annotated VCF file
-        bcftools view -i 'INFO/ANN[*].Gene_Name="APP" || INFO/ANN[*].Gene_Name="SOD21" || INFO/ANN[*].Gene_Name="DYRK1A"' \
-            {input.vcf} -o {output.genes_vcf}
+        grep -E '^(#|.*\b(APP|SOD21|DYRK1A)\b)' {input.vcf} > {output.genes_vcf}
         """
+        
+        # bcftools view -i 'INFO/ANN[*].Gene_Name="APP" || INFO/ANN[*].Gene_Name="SOD21" || INFO/ANN[*].Gene_Name="DYRK1A"' \
+        #     {input.vcf} -o {output.genes_vcf}    
+
+# Rule for creating an image with a heatmap showing the number of SNPs per individual
+rule snp_heatmap:
+    input:
+        vcf="5_snpeff/snps.annotated.vcf",
+    output:
+        heatmap_image=report("snps_heatmap.png", category="SNP Heatmap",
+                subcategory="Summary text")
+    shell:
+        """
+        bcftools query -l {input.vcf} > samples.txt
+        bcftools query -f '%CHROM\t%POS[\t%GT]\n' {input.vcf} | grep -v '#' | cut -f 3- > genotypes.txt
+        paste samples.txt genotypes.txt | awk '{print $1,$(NF-1),$NF}' | sort | uniq -c | awk '{print $2,$3,$1}' > snps_per_individual.txt
+        awk '{print $1}' snps_per_individual.txt > individuals.txt
+        awk '{print $2}' snps_per_individual.txt > snps.txt
+        python heatmap.py individuals.txt snps.txt {output.heatmap_image}
+        """    
